BEGIN;

CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD '#+kHh_C_cd4?CNB2';
CREATE ROLE anonymous ROLE authenticator;
CREATE ROLE editor ROLE authenticator;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anonymous;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO editor;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO editor;

COMMIT;
